Repository selsa-inube/inubekit-user, pull requests merged in 2024-03, with the labels that each got.

#3 Update component to use new versions of text, avatar, stack and foundations
  package-lock.json
  package.json
  src/User/User.stories.tsx
  src/User/index.tsx
  src/User/props.ts
  vite.config.ts
Labels: major

#4 Release new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#5 Adjust and export interfaces
  src/User/index.tsx
  src/User/props.ts
  src/index.ts
Labels: minor

#6 Update inubekit/user to storybook v8
  package-lock.json
  package.json
Labels: dependencies

#7 Publish new version 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation
