Repository selsa-inube/inubekit-user, pull requests merged in 2024-10, with the labels that each got.

#39 Add clickable Avatar with floating menu in User component
  package.json
  src/User/User.stories.tsx
  src/User/index.tsx
  src/User/props.ts
  src/User/styles.js
  src/index.ts
  vite.config.ts
Labels: enhancement, major

#40 Update stack dependency to latest version
  package.json
Labels: minor, dependencies

#41 fix: menu opens wherever User is clicked
  src/User/index.tsx
  src/User/styles.js
Labels: patch

#42 feat: update avatar, foundations and menu dependencies
  package.json
Labels: patch

#43 feat: position absolute for menu with user being relative
  package.json
  src/User/User.stories.tsx
  src/User/index.tsx
  src/User/styles.js
Labels: patch

#44 feat: add padding, margin, menuTopPosition, menuRightPosition props
  src/User/User.stories.tsx
  src/User/index.tsx
  src/User/styles.js
Labels: minor
